"""team tables

Revision ID: 486bb4130432
Revises: bcb8323bee82
Create Date: 2026-04-20 09:23:00.761989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '486bb4130432'
down_revision: Union[str, Sequence[str], None] = 'bcb8323bee82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('invite_code', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_invite_code'), ['invite_code'], unique=True)

    op.create_table('team_memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_memberships_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_memberships_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_team_memberships_user_left', ['user_id', 'left_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_memberships', schema=None) as batch_op:
        batch_op.drop_index('ix_team_memberships_user_left')
        batch_op.drop_index(batch_op.f('ix_team_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_memberships_team_id'))

    op.drop_table('team_memberships')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_invite_code'))

    op.drop_table('teams')
    # ### end Alembic commands ###
